# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loadDemographics <- function(inputPath, Parameters) {
    invisible(.Call(`_gonoHistoryMatching_loadDemographics`, inputPath, Parameters))
}

loadParameters <- function(inputPath, Parameters, psaParameters, NumbSim) {
    invisible(.Call(`_gonoHistoryMatching_loadParameters`, inputPath, Parameters, psaParameters, NumbSim))
}

loadCalibratioTargets <- function(inputPath, Parameters) {
    invisible(.Call(`_gonoHistoryMatching_loadCalibratioTargets`, inputPath, Parameters))
}

loadCalibrationParameters <- function(inputPath, Parameters, numbParallel) {
    invisible(.Call(`_gonoHistoryMatching_loadCalibrationParameters`, inputPath, Parameters, numbParallel))
}

updatedCalibrationParameters <- function(filename, Parameters) {
    invisible(.Call(`_gonoHistoryMatching_updatedCalibrationParameters`, filename, Parameters))
}

runmodel <- function(inputs) {
    .Call(`_gonoHistoryMatching_runmodel`, inputs)
}

