# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SIGN <- function(a, b) {
    .Call(`_gonoHistoryMatching_SIGN`, a, b)
}

nrerror <- function(error_text) {
    invisible(.Call(`_gonoHistoryMatching_nrerror`, error_text))
}

vector1 <- function(nl, nh) {
    .Call(`_gonoHistoryMatching_vector1`, nl, nh)
}

ivector <- function(nl, nh) {
    .Call(`_gonoHistoryMatching_ivector`, nl, nh)
}

cvector <- function(nl, nh) {
    .Call(`_gonoHistoryMatching_cvector`, nl, nh)
}

lvector <- function(nl, nh) {
    .Call(`_gonoHistoryMatching_lvector`, nl, nh)
}

dvector <- function(nl, nh) {
    .Call(`_gonoHistoryMatching_dvector`, nl, nh)
}

matrix <- function(nrl, nrh, ncl, nch) {
    .Call(`_gonoHistoryMatching_matrix`, nrl, nrh, ncl, nch)
}

dmatrix <- function(nrl, nrh, ncl, nch) {
    .Call(`_gonoHistoryMatching_dmatrix`, nrl, nrh, ncl, nch)
}

imatrix <- function(nrl, nrh, ncl, nch) {
    .Call(`_gonoHistoryMatching_imatrix`, nrl, nrh, ncl, nch)
}

submatrix <- function(a, oldrl, oldrh, oldcl, oldch, newrl, newcl) {
    .Call(`_gonoHistoryMatching_submatrix`, a, oldrl, oldrh, oldcl, oldch, newrl, newcl)
}

convert_matrix <- function(a, nrl, nrh, ncl, nch) {
    .Call(`_gonoHistoryMatching_convert_matrix`, a, nrl, nrh, ncl, nch)
}

f3tensor <- function(nrl, nrh, ncl, nch, ndl, ndh) {
    .Call(`_gonoHistoryMatching_f3tensor`, nrl, nrh, ncl, nch, ndl, ndh)
}

free_vector <- function(v, nl, nh) {
    invisible(.Call(`_gonoHistoryMatching_free_vector`, v, nl, nh))
}

free_ivector <- function(v, nl, nh) {
    invisible(.Call(`_gonoHistoryMatching_free_ivector`, v, nl, nh))
}

free_cvector <- function(v, nl, nh) {
    invisible(.Call(`_gonoHistoryMatching_free_cvector`, v, nl, nh))
}

free_lvector <- function(v, nl, nh) {
    invisible(.Call(`_gonoHistoryMatching_free_lvector`, v, nl, nh))
}

free_dvector <- function(v, nl, nh) {
    invisible(.Call(`_gonoHistoryMatching_free_dvector`, v, nl, nh))
}

free_matrix <- function(m, nrl, nrh, ncl, nch) {
    invisible(.Call(`_gonoHistoryMatching_free_matrix`, m, nrl, nrh, ncl, nch))
}

free_dmatrix <- function(m, nrl, nrh, ncl, nch) {
    invisible(.Call(`_gonoHistoryMatching_free_dmatrix`, m, nrl, nrh, ncl, nch))
}

free_imatrix <- function(m, nrl, nrh, ncl, nch) {
    invisible(.Call(`_gonoHistoryMatching_free_imatrix`, m, nrl, nrh, ncl, nch))
}

free_submatrix <- function(b, nrl, nrh, ncl, nch) {
    invisible(.Call(`_gonoHistoryMatching_free_submatrix`, b, nrl, nrh, ncl, nch))
}

free_convert_matrix <- function(b, nrl, nrh, ncl, nch) {
    invisible(.Call(`_gonoHistoryMatching_free_convert_matrix`, b, nrl, nrh, ncl, nch))
}

free_f3tensor <- function(t, nrl, nrh, ncl, nch, ndl, ndh) {
    invisible(.Call(`_gonoHistoryMatching_free_f3tensor`, t, nrl, nrh, ncl, nch, ndl, ndh))
}

rkck <- function(PopulationX, Parameters, psaParameters, race, gender, sexBehs, age, y[], dydx[], n, x, h, yout[], yerr[], year, month, int), ns, np) {
    invisible(.Call(`_gonoHistoryMatching_rkck`, PopulationX, Parameters, psaParameters, race, gender, sexBehs, age, y[], dydx[], n, x, h, yout[], yerr[], year, month, int), ns, np))
}

rkqs <- function(PopulationX, Parameters, psaParameters, race, gender, sexBehs, age, y[], dydx[], n, x, htry, eps, yscal[], hdid, hnext, year, month, int), ns, np) {
    invisible(.Call(`_gonoHistoryMatching_rkqs`, PopulationX, Parameters, psaParameters, race, gender, sexBehs, age, y[], dydx[], n, x, htry, eps, yscal[], hdid, hnext, year, month, int), ns, np))
}

sumVector <- function(Population1, Parameters, i_start, i_end, j_start, j_end, k_start, k_end, l_start, l_end, m_start, m_end, d_start, d_end) {
    .Call(`_gonoHistoryMatching_sumVector`, Population1, Parameters, i_start, i_end, j_start, j_end, k_start, k_end, l_start, l_end, m_start, m_end, d_start, d_end)
}

newInfections <- function(y, Parameters, race, gender, sexBeh, sexAct, age, np) {
    .Call(`_gonoHistoryMatching_newInfections`, y, Parameters, race, gender, sexBeh, sexAct, age, np)
}

derivs <- function(PopulationX, Parameters, psaParameters, race, gender, sexBehs, age, x, y, dydx, year, month, ns, np) {
    invisible(.Call(`_gonoHistoryMatching_derivs`, PopulationX, Parameters, psaParameters, race, gender, sexBehs, age, x, y, dydx, year, month, ns, np))
}

odeint <- function(PopulationX, Parameters, psaParameters, race, gender, sexBehs, age, ystart, year, month, size, ns, np) {
    invisible(.Call(`_gonoHistoryMatching_odeint`, PopulationX, Parameters, psaParameters, race, gender, sexBehs, age, ystart, year, month, size, ns, np))
}

loadInitialPopulation <- function(inputPath, PopulationX, Parameters, NumbParallel, initialInfection) {
    invisible(.Call(`_gonoHistoryMatching_loadInitialPopulation`, inputPath, PopulationX, Parameters, NumbParallel, initialInfection))
}

loadDemographics <- function(inputPath, Parameters) {
    invisible(.Call(`_gonoHistoryMatching_loadDemographics`, inputPath, Parameters))
}

loadParameters <- function(inputPath, Parameters, psaParameters, NumbSim) {
    invisible(.Call(`_gonoHistoryMatching_loadParameters`, inputPath, Parameters, psaParameters, NumbSim))
}

loadCalibratioTargets <- function(inputPath, Parameters) {
    invisible(.Call(`_gonoHistoryMatching_loadCalibratioTargets`, inputPath, Parameters))
}

loadCalibrationParameters <- function(inputPath, Parameters, numbParallel) {
    invisible(.Call(`_gonoHistoryMatching_loadCalibrationParameters`, inputPath, Parameters, numbParallel))
}

runModelDynamics <- function(PopulationX, Parameters, psaParameters, iter, np) {
    invisible(.Call(`_gonoHistoryMatching_runModelDynamics`, PopulationX, Parameters, psaParameters, iter, np))
}

updatedCalibrationParameters <- function(filename, Parameters) {
    invisible(.Call(`_gonoHistoryMatching_updatedCalibrationParameters`, filename, Parameters))
}

saveCalibratedIncidence <- function(Population, filename, Parameters) {
    invisible(.Call(`_gonoHistoryMatching_saveCalibratedIncidence`, Population, filename, Parameters))
}

saveIncidence <- function(population, filename, Parameters, runTime) {
    invisible(.Call(`_gonoHistoryMatching_saveIncidence`, population, filename, Parameters, runTime))
}

saveTrajectories <- function(population, filename, Parameters, runTime) {
    invisible(.Call(`_gonoHistoryMatching_saveTrajectories`, population, filename, Parameters, runTime))
}

runmodel <- function(inputs) {
    .Call(`_gonoHistoryMatching_runmodel`, inputs)
}

